# Generated by Django 5.0 on 2024-10-25 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendid', models.IntegerField(verbose_name='sendID')),
                ('reserveid', models.IntegerField(verbose_name='reserveID')),
                ('sendname', models.CharField(default='小江', max_length=64, verbose_name='申请者姓名')),
                ('reservename', models.CharField(default='小江', max_length=64, verbose_name='审核者姓名')),
                ('level', models.IntegerField(default=0, verbose_name='申请等级')),
                ('status', models.CharField(default='待审核', max_length=64, verbose_name='申请状态')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(verbose_name='userID')),
                ('username', models.CharField(default='小江', max_length=64, verbose_name='拥有者姓名')),
                ('key', models.CharField(max_length=6144, verbose_name='密钥')),
                ('kvector', models.CharField(default='', max_length=6144, verbose_name='初始向量')),
                ('method', models.CharField(default='', max_length=64, verbose_name='密钥类型')),
                ('level', models.IntegerField(default=0, verbose_name='等级')),
                ('length', models.IntegerField(default=0, verbose_name='长度')),
                ('remark', models.CharField(default='', max_length=1024, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(verbose_name='userID')),
                ('name', models.CharField(default='小江', max_length=64, verbose_name='拥有者姓名')),
                ('level', models.IntegerField(default=0, verbose_name='等级')),
                ('father', models.IntegerField(default=0, max_length=32, verbose_name='上级')),
                ('thing', models.CharField(blank=True, max_length=64, null=True, verbose_name='动作')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='时间')),
                ('date', models.DateField(default=datetime.date(2023, 1, 1), verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('level', models.IntegerField(default=0, verbose_name='等级')),
                ('key', models.CharField(default='', max_length=64, verbose_name='key')),
                ('father', models.IntegerField(default=0, max_length=32, verbose_name='上级')),
            ],
        ),
    ]
