# Generated by Django 5.0 on 2023-12-20 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(verbose_name='userID')),
                ('key', models.CharField(max_length=9216, verbose_name='密钥')),
                ('level', models.IntegerField(default=0, verbose_name='等级')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(verbose_name='userID')),
                ('thing', models.CharField(blank=True, max_length=64, null=True, verbose_name='动作')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='时间')),
                ('date', models.DateField(default=datetime.date(2023, 1, 1), verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('level', models.IntegerField(default=0, verbose_name='等级')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('father', models.CharField(max_length=32, verbose_name='上级')),
            ],
        ),
    ]
