# Generated by Django 5.0 on 2023-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='kvector',
            field=models.CharField(default='', max_length=9216, verbose_name='初始向量'),
        ),
        migrations.AddField(
            model_name='keys',
            name='method',
            field=models.CharField(default='', max_length=64, verbose_name='密钥类型'),
        ),
    ]
