# Generated by Django 5.0 on 2023-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0003_keys_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='remark',
            field=models.CharField(default='', max_length=1024, verbose_name='备注'),
        ),
    ]
