# Generated by Django 5.0 on 2023-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0005_alter_keys_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='kvector',
            field=models.CharField(default='', max_length=1024, verbose_name='初始向量'),
        ),
    ]
