# Generated by Django 5.0 on 2023-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0006_alter_keys_kvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='username',
            field=models.CharField(default='小江', max_length=64, verbose_name='拥有者姓名'),
        ),
    ]
