# Generated by Django 5.0 on 2023-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0009_applys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='father',
            field=models.IntegerField(default=0, max_length=32, verbose_name='上级'),
        ),
    ]
