# Generated by Django 5.0 on 2023-12-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0011_logs_level_logs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='father',
            field=models.IntegerField(default=0, max_length=32, verbose_name='上级'),
        ),
    ]
