# Generated by Django 5.0 on 2023-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0012_logs_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='key',
            field=models.CharField(default='', max_length=64, verbose_name='key'),
        ),
    ]
